version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.7.0
    container_name: airflow_webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      # postgresql+psycopg2://usuario:contraseña@host:puerto/base_de_datos
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}postgres@postgres:5432/${POSTGRES_DB}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: >
      bash -c "airflow db upgrade &&
               airflow users create --username admin --password admin --firstname Lara --lastname Lara --role Admin --email berenice.ledesma12345@gmail.com &&
               airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.7.0
    container_name: airflow_scheduler
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: airflow scheduler

volumes:
  postgres_data:
